# Generated by Django 6.0.2 on 2026-04-08 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_teacherload_subject_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='disciplinaryrecord',
            name='action_taken',
        ),
        migrations.RemoveField(
            model_name='disciplinaryrecord',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='date_enrolled',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='section',
        ),
        migrations.RemoveField(
            model_name='excuseletter',
            name='staff_remarks',
        ),
        migrations.RemoveField(
            model_name='section',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='middle_initial',
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.section'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='afternoon_status',
            field=models.CharField(default='PRESENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='dismissal_status',
            field=models.CharField(default='PRESENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='morning_status',
            field=models.CharField(default='PRESENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='disciplinaryrecord',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='excuseletter',
            name='status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='grade_level',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='CommunityServiceRecord',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='is_flagged',
        ),
    ]
