# Generated by Django 5.1.6 on 2026-04-14 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_attendancerecord_afternoon_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_signature',
        ),
        migrations.AlterField(
            model_name='section',
            name='beadle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beadle_of_section', to='core.student'),
        ),
    ]
