# Generated by Django 5.1.6 on 2026-04-14 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_student_parent_signature_alter_section_beadle'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='section',
            name='beadle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beadle_of', to='core.student'),
        ),
    ]
