# Generated by Django 5.1.6 on 2026-04-23 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_student_parent_signature_alter_section_beadle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplinaryrecord',
            old_name='action_taken',
            new_name='sanction',
        ),
        migrations.AddField(
            model_name='disciplinaryrecord',
            name='is_excused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disciplinaryrecord',
            name='is_served',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disciplinaryrecord',
            name='offense_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disciplinaryrecord',
            name='record_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='disciplinaryrecord',
            name='time_of_incident',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('OLD', 'Old'), ('NEW', 'New'), ('TRANSFEREE', 'Transferee')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(default='PRESENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='code',
            field=models.CharField(help_text='e.g., 2025-2026', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='prefix',
            field=models.CharField(help_text='e.g., Mr., Ms., Bro., Fr.', max_length=10),
        ),
        migrations.CreateModel(
            name='CommunityServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_served', models.DateField()),
                ('hours_served', models.IntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_service_records', to='core.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
