# Generated by Django 5.1.6 on 2026-04-25 08:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_action_taken_disciplinaryrecord_sanction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='excuseletter',
            name='attendance_record',
        ),
        migrations.AddField(
            model_name='excuseletter',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section')),
            ],
            options={
                'unique_together': {('date', 'section')},
            },
        ),
        migrations.AddField(
            model_name='excuseletter',
            name='daily_attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excuse_letters', to='core.dailyattendance'),
        ),
        migrations.CreateModel(
            name='PeriodAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_number', models.IntegerField(choices=[(1, '1st Period'), (2, '2nd Period'), (3, '3rd Period'), (4, '4th Period'), (5, '5th Period'), (6, '6th Period'), (7, '7th Period')])),
                ('is_locked', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('daily_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='core.dailyattendance')),
                ('submitted_by', models.ForeignKey(help_text='Beadle who submitted', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.student')),
            ],
            options={
                'unique_together': {('daily_attendance', 'period_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentPeriodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('UU', 'Unprescribed Uniform'), ('UH', 'Unprescribed Haircut'), ('ID', 'No ID'), ('CL', 'Campus Leave')], default='P', max_length=2)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.periodattendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_code', models.CharField(max_length=2)),
                ('new_code', models.CharField(max_length=2)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.studentperiodrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AttendanceBatch',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
