# Generated by Django 5.1.6 on 2026-04-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_attendancerecord_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperiodrecord',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentperiodrecord',
            name='original_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
