# Generated by Django 5.1.6 on 2026-04-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_studentperiodrecord_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodattendance',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
