# Generated by Django 5.1.6 on 2026-05-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_student_birthplace_student_brothers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense_type', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('default_demerits', models.IntegerField(default=5)),
                ('default_sanction', models.CharField(blank=True, max_length=100, null=True)),
                ('default_count', models.FloatField(default=1.0)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
