# Generated by Django 5.1.6 on 2026-05-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_offense'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
