# Generated by Django 5.1.6 on 2026-05-25 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_student_father_signature_student_guardian_signature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcuseLetterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_requested_for', models.DateField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excuse_requests', to='core.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
