# Generated by Django 5.1.6 on 2026-05-25 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_excuseletterrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='excuseletterrequest',
            name='excuse_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.excuseletter'),
        ),
        migrations.AddField(
            model_name='excuseletterrequest',
            name='violation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
