# Attendance Codes
ATTENDANCE_CODE_PRESENT = 'P'
ATTENDANCE_CODE_ABSENT = 'A'
ATTENDANCE_CODE_LATE = 'L'
ATTENDANCE_CODE_UNPRESCRIBED_UNIFORM = 'UU'
ATTENDANCE_CODE_UNPRESCRIBED_HAIRCUT = 'UH'
ATTENDANCE_CODE_NO_ID = 'ID'
ATTENDANCE_CODE_CAMPUS_LEAVE = 'CL'

ATTENDANCE_CHOICES = [
    (ATTENDANCE_CODE_PRESENT, 'Present'),
    (ATTENDANCE_CODE_ABSENT, 'Absent'),
    (ATTENDANCE_CODE_LATE, 'Late'),
    (ATTENDANCE_CODE_UNPRESCRIBED_UNIFORM, 'Unprescribed Uniform'),
    (ATTENDANCE_CODE_UNPRESCRIBED_HAIRCUT, 'Unprescribed Haircut'),
    (ATTENDANCE_CODE_NO_ID, 'No ID'),
    (ATTENDANCE_CODE_CAMPUS_LEAVE, 'Campus Leave'),
]
